name: area_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.1.6
  cupertino_icons: ^1.0.2
  flutter_login: ^4.1.1
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5 
  flutter_swiper_null_safety: ^1.0.2
  cloud_firestore: ^4.1.0
  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  http: ^0.13.4
  get: ^4.6.5
  fluttericon: ^2.0.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  flutter_profile_picture: ^2.0.0
  firebase_storage: ^11.0.6
  transparent_image: ^2.0.0
  provider: ^6.0.4
  circular_profile_avatar: ^2.0.5
  font_awesome_flutter: ^10.3.0
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

 
  assets:
     - assets/images/logo.png
     - assets/images/marker.png
     - assets/images/google.png

 


  
